apiVersion: batch/v1
kind: Job
metadata:
  name: hook
  namespace: aws-for-fluent-bit
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  template:
    metadata:
      labels:
        app: "my-app"
    spec:
      restartPolicy: Never
      containers:
      - name: add-labels
        image: bitnami/kubectl
        command: ["sh", "-c", "kubectl -n aws-for-fluent-bit label pod --all test-local-git=test-local-git test-from-argo=test-from-argo"]
      serviceAccountName: aws-for-fluent-bit
